- name: Create scripts directory
  file:
    path: /home/{{ user_1 }}/scripts
    state: directory
    owner: "{{ user_1 }}"
    group: "{{ user_1 }}"
    mode: '0700'

- name: Clone NeonEnvConfig
  ansible.builtin.git:
    repo: 'https://github.com/alfred-c-scott/NeonEnvConfig.git'
    dest: /home/{{ user_1 }}/scripts
    version: master
    force: yes
  become: yes
  become_user: "{{ user_1 }}"

# - name: Set ownership of the cloned repository
#   ansible.builtin.file:
#     path: /home/{{ user_1 }}/scripts
#     owner: "{{ user_1 }}"
#     group: "{{ user_1 }}"
#     recurse: yes