---
- hosts: all
  become: true
  vars_files:
    - vars/user_vars.yml
  tasks:

  - name: Update repository cache && dist-upgrade
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: Install packages
    apt:
      name:
        - neovim
        - tmux
        - xrdp
        - git
      state: latest
    when: ansible_distribution == "Ubuntu"

  - include_tasks: modules/add_git_ssh_key.yml

  - include_tasks: modules/git_config.yml

  - include_tasks: modules/git_clone_neon_setup.yml

  - name: Reboot the system
    reboot:
      reboot_timeout: 600
    when: ansible_distribution == "Ubuntu"

  - name: Wait for the system to come back up
    wait_for_connection:
      delay: 10
      timeout: 300
    when: ansible_distribution == "Ubuntu"